In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4], dtype=np.int32)
x.data

In [3]:
x.__array_interface__   

{'data': (31710640, False),
 'descr': [('', '<i4')],
 'shape': (4,),
 'strides': None,
 'typestr': '<i4',
 'version': 3}

In [5]:
x.__array_interface__['data'][0]  #数据的内存地址

31710640

-

In [6]:
help(np.newaxis)

Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __repr__(self, /)
 |      Return repr(self).



In [7]:
x = np.array([1,2,3,4])
x[np.newaxis, :]

array([[1, 2, 3, 4]])

In [8]:
x[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [9]:
x[np.newaxis, :] * x[:, np.newaxis]

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

- 对角线

In [11]:
from numpy.lib.stride_tricks import as_strided

In [21]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]], dtype=np.int8)
x_diag = as_strided(x, shape=(3, ), strides=((3+1) * x.itemsize, ))
x_diag

array([1, 5, 9], dtype=int8)

In [24]:
as_strided(x[0, 1:], shape=(2, ), strides=((3 + 1) * x.itemsize, ))

array([2, 6], dtype=int8)

In [25]:
as_strided(x[1:, 0], shape=(2, ), strides=((3 + 1) * x.itemsize, ))

array([4, 8], dtype=int8)