### 1.3.2 数组的数值操作

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [3]:
2 ** a

array([ 2,  4,  8, 16])

所有操作是在元素级别上的

In [4]:
b = np.ones(4) + 1
b

array([ 2.,  2.,  2.,  2.])

In [9]:
np.ones([4,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

- 对比

In [10]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True], dtype=bool)

数组级别的对比：

In [11]:
c = np.array([1,2,3,4])
np.array_equal(a,b)

False

In [12]:
np.array_equal(a,c)

True

- 逻辑操作

In [13]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False], dtype=bool)

In [14]:
np.logical_and(a,b)

array([ True, False, False, False], dtype=bool)

In [26]:
np.all([True, False, True])

False

In [27]:
np.any([True, False])

True

In [28]:
a = np.zeros((100,100))
np.any(a != 0)

False

In [29]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a <= b ) & (b <= c)).all()

True

- 变换

In [15]:
help(np.triu)

Help on function triu in module numpy.lib.twodim_base:

triu(m, k=0)
    Upper triangle of an array.
    
    Return a copy of a matrix with the elements below the `k`-th diagonal
    zeroed.
    
    Please refer to the documentation for `tril` for further details.
    
    See Also
    --------
    tril : lower triangle of an array
    
    Examples
    --------
    >>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 0,  8,  9],
           [ 0,  0, 12]])



In [16]:
help(np.tril)

Help on function tril in module numpy.lib.twodim_base:

tril(m, k=0)
    Lower triangle of an array.
    
    Return a copy of an array with elements above the `k`-th diagonal zeroed.
    
    Parameters
    ----------
    m : array_like, shape (M, N)
        Input array.
    k : int, optional
        Diagonal above which to zero elements.  `k = 0` (the default) is the
        main diagonal, `k < 0` is below it and `k > 0` is above.
    
    Returns
    -------
    tril : ndarray, shape (M, N)
        Lower triangle of `m`, of same shape and data-type as `m`.
    
    See Also
    --------
    triu : same thing, only for the upper triangle
    
    Examples
    --------
    >>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 0,  0,  0],
           [ 4,  0,  0],
           [ 7,  8,  0],
           [10, 11, 12]])



In [18]:
a = np.triu(np.ones([3,3]), 1)
a

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [19]:
a.T

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  0.]])

- 计算求和

In [20]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [21]:
x.sum()

10

In [22]:
x = np.array([
        [1,1],
        [2,2]
    ])
x.sum(axis=0) #列求和

array([3, 3])

In [23]:
x.sum(axis=1) #行求和

array([2, 4])

在高维：

In [24]:
x = np.random.rand(2,2,2)
x

array([[[ 0.05796886,  0.67891635],
        [ 0.02699877,  0.57971882]],

       [[ 0.74347983,  0.87842613],
        [ 0.68821555,  0.5582138 ]]])

In [25]:
x.sum(axis=2)[0,1]

0.60671759255625379

- 

### 1.3.3 数据的更多内容

赋值不会改变类型：

In [31]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [33]:
a[0] = 1.9  #浮点数被截取为整数
a

array([1, 2, 3])

In [34]:
a[0] = 10
a

array([10,  2,  3])

强制投射：

In [35]:
a = np.array([1.4, 1.2, 2.3])
b = a.astype(int) #截取整数
b

array([1, 1, 2])

四舍五入：

In [36]:
a = np.array([1.2, 1.5, 2.1, 4.6])
b = np.around(a)
b #仍然是浮点数

array([ 1.,  2.,  2.,  5.])

- 不同数据类型的大小

整数（带符号）：

|类型|字节数|
|-----|-----|
|int8| 8 bits|
|int16| 16 bits|
|int64|64 bits|

In [37]:
np.array([1], dtype=int).dtype

dtype('int64')

In [39]:
np.iinfo(np.int32).max, 2**31 - 1

(2147483647, 2147483647)

无符号整数：

|类型|字节数|
|-----|-----|
|uint8| 8 bits|
|uint16| 16 bits|
|uint64|64 bits|

In [40]:
np.iinfo(np.uint32).max, 2**32 - 1

(4294967295, 4294967295)

#### 1.3.3.2 结构化数据类型

|名称|类型|
|-----|-----|
|sensor_code|4个字母的字符|
|position|浮点|
|value|浮点|

In [53]:
samples = np.zeros((6,), dtype=[('sensor_code','S4'), ('position', float), ('value', float)]) #长度为6，每个位置3种类型，用0填充
samples

array([(b'', 0.0, 0.0), (b'', 0.0, 0.0), (b'', 0.0, 0.0), (b'', 0.0, 0.0),
       (b'', 0.0, 0.0), (b'', 0.0, 0.0)], 
      dtype=[('sensor_code', 'S4'), ('position', '<f8'), ('value', '<f8')])

In [54]:
samples.dtype.names

('sensor_code', 'position', 'value')

In [55]:
samples.dtype

dtype([('sensor_code', 'S4'), ('position', '<f8'), ('value', '<f8')])

用名称访问：

In [57]:
samples['sensor_code']

array([b'', b'', b'', b'', b'', b''], 
      dtype='|S4')

In [58]:
samples['S4']

ValueError: no field of name S4

In [62]:
samples[samples['sensor_code'] == 0]

/root/miniconda3/envs/sun01/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if __name__ == '__main__':
/root/miniconda3/envs/sun01/lib/python3.5/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  if __name__ == '__main__':


(b'', 0.0, 0.0)